Feature v1.0.3 lecture type
711skhu/front_core pull request #12
Opened 2019-05-19 09:57 UTC by jihyuno301

<h4>강의카테고리</h4>
![image](https://user-images.githubusercontent.com/37688041/57980498-679be180-7a67-11e9-9260-c5a19f0da306.png)
***
<h4>강의소개수정</h4>
![image](https://user-images.githubusercontent.com/37688041/57980539-d1b48680-7a67-11e9-8c28-82a524ae9d46.png)
***
<h4>강의소개</h4>
![image](https://user-images.githubusercontent.com/37688041/57980554-e264fc80-7a67-11e9-8e7c-403edc4ca03d.png)

2019-05-19 13:24 UTC, shouwn commented on src/components/lecture/LectureList.vue
> +<style >
이 부분에 띄어쓰기는 없어도 될 것 같아요.

2019-05-19 13:25 UTC, shouwn commented on index.html
> +  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
무엇을 위한 링크인지 주석으로 자세히 설명해주시면 좋을 것 같아요.

2019-05-19 13:27 UTC, shouwn commented on src/components/lecture_type/LectureInfoMd.vue
> +  }
전체적으로 필요없는 줄바꿈이나 공백은 줄이는 게 좋을 것 같아요.

2019-05-19 13:28 UTC, shouwn commented on src/components/lecture_type/LectureInfoMd.vue
> +</template>
lodash로 300ms 당 한 번씩 input 이벤트가 발생하는 것 외에는 로직이 없기 때문에
컴포넌트를 나누기 보다는 합치는 것도 좋을 것 같네요.

2019-05-19 13:30 UTC, shouwn commented on src/components/lecture_type/info_admin.vue
> +  </div>
이건 원래 요구사항에 없던 제안 사항이긴 한데

현재는 강좌의 설명만 수정하지만 여기에 강좌 이름도 수정할 수 있으면 어떨까요?

2019-05-19 13:32 UTC, shouwn commented on src/components/lecture_type/info_admin.vue
> +  </div>
추가로 미리 보기도 있으면 좋겠네요.

2019-05-19 13:33 UTC, shouwn commented on src/components/lecture_type/info_admin.vue
> +      }
이 부분은 나중에 서버로 전송하는 로직이 들어갈 메소드이죠?

그러면 clickBtn 보다는 좀 더 목적성이 있는 이름이 있으면 좋을 것 같아요. 그리고 주석으로 나중에 무슨 로직을 추가할지도 적혀 있으면 좋겠네요.0

2019-05-19 13:34 UTC, jeenie commented on index.html
> +  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
이 링크는 강의소개 이미지 우측 아이콘을 위한걸로 알고 있습니다!

2019-05-19 13:35 UTC, shouwn commented on src/components/lecture_type/info_user.vue
> +        selectedImage: '',
images에서 배열을 정의하는 것보다 export default 밖에서 const로 선언하고 정의하는 게 좀 더 좋을 것 같아요.

2019-05-19 13:37 UTC, shouwn commented on src/components/lecture_type/problem__type.vue
> +      </sui-grid-row>
맞은 문제 틀린 문제 덜푼 문제도 같은 형태이기 때문에 v-for로 중복을 줄이는 게 좋을 것 같아요.

관련 데이터를 배열에 저장하고 v-for로 반복문을 돌면 어떨까요?

2019-05-19 13:39 UTC, shouwn commented on src/components/lecture_type/problem__type.vue
> +      const { typeTotalProblemCnt, typeCorrectProblemCnt, typeIncorrectProblemCnt } = this;
이 문장은 어떤 것 때문에 존재하는 것인가요?

2019-05-19 13:40 UTC, shouwn commented
전체적으로 디렉토리 이름이나 파일 이름이 통일 되어 있지 않네요.
모두 카멜 케이스로 통일 부탁드려요.

2019-05-19 13:42 UTC, shouwn requested changes
전체적으로 디렉토리 이름과 파일명이 통일되어 있지 않네요.
모두 카멜 케이스로 수정 부탁드려요.

2019-05-31 12:50 UTC, shouwn approved these changes

2019-05-31 13:33 UTC, jeenie approved these changes

2019-05-31 15:46 UTC, merged