LectureToggle 컴포넌트 수정
711skhu/front_core pull request #26
Opened 2019-06-09 13:42 UTC by jeenie

* semantic-ui Toggle에서 vuetify Toggle로 변경했습니다.

2019-06-09 13:48 UTC, shouwn requested changes

2019-06-09 13:48 UTC, shouwn commented on src/App.vue
> +  }
App.vue 는 수정해주세요.

2019-06-09 13:48 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +    props: ['lecture'],
props 는 항상 타입과 설명이 명시되어야 합니다.

2019-06-09 13:48 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +    }
사용하지 않는 created 는 삭제해 주세요.

2019-06-09 13:48 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +    },
템플릿을 보면 isProfessor는 사용하는 부분이 없는데 어디에 쓰이는 건가요?

2019-06-09 13:48 UTC, shouwn commented on src/components/lecture/LectureToggle.vue
> +  </v-container>
Lecture 에서만 사용할 거라면 이렇게 컴포넌트로 분리하지 않고 v-switch를 LectureToggle이 사용되는 곳에서 직접 사용해도 좋을 것 같습니다.

2019-06-13 02:18 UTC, shouwn approved these changes

2019-06-15 03:29 UTC, jihyuno301 approved these changes

2019-06-15 11:28 UTC, merged