강의 목록 페이지 구현 완료
711skhu/front_core pull request #9
Opened 2019-04-30 09:34 UTC by jeenie

![강의 목록](https://user-images.githubusercontent.com/38181303/56952676-cf03f700-6b75-11e9-9a01-91f1bd998f97.png)

- 강의 이름과 교수명 출력
- 활성화를 위한 Toggle Switch 구현
- 마우스를 오버할 때 테두리 그림자 효과와 강의 이름이 파란색으로 변경되도록 구현

2019-05-04 09:17 UTC, shouwn commented on src/App.vue
>  </style>
머지할 때는 다른 분들 코드와 충돌이 될 수 있기 때문에
App.vue 는 원래 상태로 유지해주세요.

2019-05-04 09:22 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +  }
item:hover 로 하는 것도 좋지만 해당 속성이 다른 곳에서도 쓰기이 때문에 slot을 활용하여 컴포넌트로 따로 만들어서 재활용하는 방식도 좋을 것 같아요.

2019-05-04 09:25 UTC, shouwn requested changes

2019-05-04 09:25 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +            </div>
강좌 정보는 학생도 볼 수 있고 교수도 볼 수 있기 때문에 공통 부분을 추출할 수 있을 것 같습니다.

여기서는 타이틀과 교수가 될 것 같은데요. 

학생과 교수 공통으로 쓰는 타이틀과 교수 정보를 보여주는 컴포넌트
교수의 경우 강좌를 열지 말지 결정하기 위한 체크박스가 들어간 컴포넌트

이렇게 두 가지 컴포넌트로 만드는 게 좋을 것 같습니다.

2019-05-07 03:18 UTC, jeenie commented on src/App.vue
>  </style>
네 수정하겠습니다!

2019-05-08 15:57 UTC, shouwn commented on src/components/lecture/LectureToggle.vue
> +</script>
checkbox 컴포넌트는 너무 단순해서 꼭 컴포넌트를 안 만들어도 될 것 같아요.

2019-05-08 15:59 UTC, shouwn requested changes

2019-05-08 15:59 UTC, shouwn commented on src/components/lecture/LectureItem.vue
> +    >
hover 하는 것과 클릭 이벤트를 구현한 것은 좋지만 v-for 형태로 만들 필요는 없다고 생각합니다.

v-for로 여러 목록을 보여주는 것은 다른 곳에서 하고 여기서는 <div> 하나만 있으면 될 것 같아요.

추가로 slot에 이름을 정할 필요도 없을 것 같아요

2019-05-12 04:49 UTC, shouwn approved these changes

2019-05-14 03:17 UTC, jihyuno301 commented on src/components/lecture/LectureItem.vue
> +      clickItem (selectedItem, index) {
components/problem아래의 뷰파일에 동일한 메소드가 존재하는데 이 또한 따로 만들어서 사용가능하지 않을까요?

2019-05-14 04:06 UTC, jeenie commented on src/components/lecture/LectureItem.vue
> +      clickItem (selectedItem, index) {
추후 개선하겠습니다...

2019-05-14 04:06 UTC, merged